/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

 export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/Bill": {
    get: {
      parameters: {
        query: {
          deadline?: parameters["rowFilter.Bill.deadline"];
          payee?: parameters["rowFilter.Bill.payee"];
          amount?: parameters["rowFilter.Bill.amount"];
          category?: parameters["rowFilter.Bill.category"];
          id?: parameters["rowFilter.Bill.id"];
          userId?: parameters["rowFilter.Bill.userId"];
          completedDate?: parameters["rowFilter.Bill.completedDate"];
          archived?: parameters["rowFilter.Bill.archived"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Bill"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Bill */
          Bill?: definitions["Bill"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          deadline?: parameters["rowFilter.Bill.deadline"];
          payee?: parameters["rowFilter.Bill.payee"];
          amount?: parameters["rowFilter.Bill.amount"];
          category?: parameters["rowFilter.Bill.category"];
          id?: parameters["rowFilter.Bill.id"];
          userId?: parameters["rowFilter.Bill.userId"];
          completedDate?: parameters["rowFilter.Bill.completedDate"];
          archived?: parameters["rowFilter.Bill.archived"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          deadline?: parameters["rowFilter.Bill.deadline"];
          payee?: parameters["rowFilter.Bill.payee"];
          amount?: parameters["rowFilter.Bill.amount"];
          category?: parameters["rowFilter.Bill.category"];
          id?: parameters["rowFilter.Bill.id"];
          userId?: parameters["rowFilter.Bill.userId"];
          completedDate?: parameters["rowFilter.Bill.completedDate"];
          archived?: parameters["rowFilter.Bill.archived"];
        };
        body: {
          /** Bill */
          Bill?: definitions["Bill"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  Bill: {
    /** Format: date */
    deadline?: string;
    /** Format: text */
    payee?: string;
    /** Format: double precision */
    amount?: number;
    /** Format: text */
    category?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: uuid */
    userId?: string;
    /** Format: date */
    completedDate?: string;
    /** Format: boolean */
    archived?: boolean;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description Bill */
  "body.Bill": definitions["Bill"];
  /** Format: date */
  "rowFilter.Bill.deadline": string;
  /** Format: text */
  "rowFilter.Bill.payee": string;
  /** Format: double precision */
  "rowFilter.Bill.amount": string;
  /** Format: text */
  "rowFilter.Bill.category": string;
  /** Format: bigint */
  "rowFilter.Bill.id": string;
  /** Format: uuid */
  "rowFilter.Bill.userId": string;
  /** Format: date */
  "rowFilter.Bill.completedDate": string;
  /** Format: boolean */
  "rowFilter.Bill.archived": string;
}

export interface operations {}

export interface external {}
