# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Create a new app bundle to Play Store: Internal Track"
  lane :internal do
    gradle(task: 'clean')
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
    end

  desc "Submit a new build to Play Store: Internal Track"
  lane :internal do
    gradle(task: 'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store(track: 'internal')
    end
end
