name: Update database types

on:
  schedule:
    # sets the action to run daily. You can modify this to run the action more or less frequently
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - run: |
          npm run update-types
        env:
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          SUPABASE_ANON_KEY: ${{secrets.SUPABASE_URL}}
      - name: check for file changes
        uses: technote-space/get-diff-action@v4.0.1
        id: git_status
        with:
          FILES: |
            src/types/supabase.ts
      - name: Commit files
        if: env.GIT_DIFF
        run: |
          git add src/types/supabase.ts
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "billy-github-actions[bot]"
          git commit -m "Update database types" -a
      - name: Push changes
        if: env.GIT_DIFF
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
